NUM_SUBMISSION_IN_DIR = 100000

DATA_HOME_WINDOWS = r"C:\Users\kumniti\prog\Projects\online_judge\data"
SUBMISSION_DATA_BASE_PATH = DATA_HOME_WINDOWS + r"\submissions"
PROBLEM_DATA_BASE_PATH = DATA_HOME_WINDOWS + r"\problems"
TESTCASES_DIR = r"\testcases"

ENVIRONMENT = "WINDOWS_1"
ENV_WINDOWS1 = "WINDOWS_1"

INITIAL_VERDICT_TEXT = "Processing"
SECURITY_CHECK_FAILED_VERDICT = "Security check failed for your code"
