# Generated by Django 4.0.5 on 2022-06-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemLanuageRelation',
            new_name='ProblemLanguageRelation',
        ),
        migrations.RenameField(
            model_name='problemlanguagerelation',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
