# Generated by Django 4.0.5 on 2022-06-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_problemlanuagerelation_problemlanguagerelation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
