# Generated by Django 4.0.6 on 2022-07-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_userproblemrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProblemRelation',
        ),
    ]
